name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - 'packages/container/**'

defaults:
  run:
    working-directory: packages/container

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@master
        with:
          node-version: 12

      - name: Install dependencies
        run: npm ci

      # - name: Lint
      #   run: npm run lint

      # - name: Test
      #   run: npm run test

      - name: Build
        run: npm run build

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy
        run: surge ./dist ${{ secrets.CONTAINER_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
